"""
Multi-Agent Orchestrator using Microsoft AutoGen.

This module provides an enterprise-grade multi-agent system orchestrator
designed for complex planning and coding tasks using Azure OpenAI models.
"""

from typing import Dict, Any, Optional, List
import os
import logging
import autogen

# Set up module-level logging
logger = logging.getLogger(__name__)

class MultiAgentOrchestrator:
    """
    Orchestrates multi-agent workflows using Microsoft AutoGen.
    
    Attributes:
        llm_config (Dict[str, Any]): Configuration for the Language Learning Model.
        user_proxy (autogen.UserProxyAgent): The user proxy agent.
        assistant (autogen.AssistantAgent): The assistant agent.
    """

    def __init__(self, config_list: Optional[List[Dict[str, Any]]] = None) -> None:
        """
        Initializes the MultiAgentOrchestrator with required configurations.

        Args:
            config_list (Optional[List[Dict[str, Any]]]): List of configuration dictionaries for LLM.
                If not provided, it attempts to load from environment variables.
        """
        try:
            if not config_list:
                # Typically, in Azure, we'd use environment variables for this.
                config_list = [{
                    "model": os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", "gpt-4o"),
                    "api_key": os.getenv("AZURE_OPENAI_API_KEY"),
                    "base_url": os.getenv("AZURE_OPENAI_ENDPOINT"),
                    "api_type": "azure",
                    "api_version": os.getenv("AZURE_OPENAI_API_VERSION", "2024-02-15-preview"),
                }]
            
            self.llm_config: Dict[str, Any] = {
                "config_list": config_list,
                "timeout": 120,
                "temperature": 0.0,
                "seed": 42  # For reproducible results
            }

            self._initialize_agents()
            logger.info("MultiAgentOrchestrator initialized successfully.")

        except Exception as e:
            logger.error(f"Failed to initialize MultiAgentOrchestrator: {e}", exc_info=True)
            raise RuntimeError(f"Initialization error: {e}") from e

    def _initialize_agents(self) -> None:
        """
        Initializes the AutoGen agents required for the orchestrator.
        """
        self.assistant = autogen.AssistantAgent(
            name="Planner_and_Coder",
            llm_config=self.llm_config,
            system_message="""You are a senior Azure AI Engineer at Deloitte. 
            You are responsible for planning, designing, and writing robust, 
            enterprise-grade Python code. Always ensure strict type hinting, 
            comprehensive Google-style docstrings, and robust error handling."""
        )

        self.user_proxy = autogen.UserProxyAgent(
            name="User_Proxy",
            human_input_mode="NEVER",
            max_consecutive_auto_reply=10,
            is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
            code_execution_config={
                "work_dir": "agent_workspace",
                "use_docker": False, # Set to True in actual isolated environments
            },
            system_message="A human admin executing the plans and code generated by the Planner_and_Coder."
        )

    def initiate_task(self, task_description: str) -> str:
        """
        Initiates a multi-agent task workflow.

        Args:
            task_description (str): A detailed description of the task to be executed.

        Returns:
            str: A summary of the conversation or the final result.

        Raises:
            ValueError: If the task description is empty or invalid.
        """
        if not task_description or not isinstance(task_description, str):
            logger.error("Invalid task description provided.")
            raise ValueError("Task description must be a non-empty string.")

        try:
            logger.info(f"Initiating task: {task_description[:50]}...")
            chat_result = self.user_proxy.initiate_chat(
                self.assistant,
                message=task_description
            )
            # chat_result is an autogen ChatResult object
            return chat_result.summary if hasattr(chat_result, 'summary') else str(chat_result)
            
        except Exception as e:
            logger.error(f"Error during task execution: {e}", exc_info=True)
            raise
